dist: trusty
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 https://distrowatch.com/table.php?distribution=nixos

notifications:
  irc:
    channels:
      - "irc.freenode.net#krebs-bots"
    skip_join: true
